red="\033[38;5;9m"
green="\033[1;38;5;2m"
blue="\033[38;5;4m"
magenta="\033[38;5;5m"
purple="\033[38;5;5m"
yellow="\033[38;5;3m"
creset="\033[0m"

echo -e " "
echo -e " Please wait.. "
echo -e " "
echo -e " ${blue} > Send Ping to Universe..  █████████████████████████████ ${green}> Ping Delivered"
echo -e " "
echo -e " ░░ You've got new message! ░░"
echo -e " ${magenta} ALIEN: ${red}Alien is Typing..."
echo -e " ${magenta} ALIEN: ${red}PONG.."
echo -e " ${magenta} ALIEN: ${red}Alien is Typing..."
echo -e " "
echo -e "    ${magenta} ✧ Assalamualaikum  Kakak ✧        ✧            ✧    "
echo -e "    ${magenta}    ✧      ✧          ✧          ✧          ✧    "
echo -e "    ${magenta} ✧   ✧ Selamat Bekerja, Jangan Lupa Diniatkan untuk Ibadah ✧        ✧    "
echo -e "    ${magenta}✧   ▄▀▀▀▄▄▄▄▄▄▄▀▀▀▄   ✧  ${red}__ ${green}__ ${blue}__ __"
echo -e "    ${magenta}   ✧█▒▒░░░░░░░░░▒▒█      ${red}\\ V${green}\\ V${blue}\\ V /"
echo -e "    ${magenta} ▄▄  █░░█░░░░░█░░█ ✧     ${red} \\_/${green}\\_/${blue}\\_/"
echo -e "    ${magenta}█░░█  █░░░▀█▀░░░█     ✧              ✧          "
echo -e "    ${magenta}█░░█  ▀▄░░░░░░░▄▀ ✧      Semangat Ngodingnya :) ${CRESET}"
echo -e " ${CRESET}"
